### ISSUE TITLE
torch报错不支持bool类型tensor的-操作

### ISSUE THREAD

**Issue by Yeuoly** [minghaochen/chatglm3-base-tuning#1]
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

**Comment by minghaochen** [comment]
modeling_chatglm 691行 改一下
`full_attention_mask -= padding_mask.unsqueeze(-1).int() - 1`
