### ISSUE TITLE
训练过程中报错显存不够，但是明显有剩余显存。

### ISSUE THREAD

**Issue by DeMoth-1** [minghaochen/chatglm3-base-tuning#10]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU 1 has a total capacty of 22.00 GiB of which 20.28 GiB is free. Of the allocated memory 527.15 MiB is allocated by PyTorch, and 2.85 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by minghaochen** [comment]
全量微调？

**Comment by DeMoth-1** [comment]
数据集问题，已解决
