### ISSUE TITLE
关于微调数据的问题

### ISSUE THREAD

**Issue by 948024326** [minghaochen/chatglm3-base-tuning#2]
作者您好，想问下您的项目可以做chatGLM3-6b-base的微调吗？ 
意思是比如我有一个知识库，里面写了100个问答对，然后通过微调训练后得到的新的模型可以得到一个能回答我自己知识库的模型嘛？
如果可以的话，要训练的数据的格式有什么要求嘛？  谢谢

**Comment by minghaochen** [comment]
是的

项目中附了一个数据集示例了，可以参考着改就行哈
